name: "online_catalog"

services:
  frontend-dev:
    profiles: ["development"]
    build:
      context: ./frontend
      target: development
    ports:
      - "4200:4200"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    networks:
      - catalog_network
    environment:
      - DOMAIN=${DOMAIN}
    restart: unless-stopped

  frontend-prod:
    profiles: ["production"]
    build:
      context: ./frontend
      target: production
    ports:
      - "${FRONT_PORT}:80"
      - "${FRONT_HTTPS}:443"
    volumes:
      - ./ssl:/etc/nginx/ssl:ro
    networks:
      - catalog_network
    environment:
      - DOMAIN=${DOMAIN}
    restart: unless-stopped

  backend:
    profiles: ["_base"]
    build:
      context: ./backend
      target: ${COMPOSE_PROFILES}
    depends_on:
      - mongodb
    networks:
      - catalog_network
    environment:
      - MONGO_URL=${MONGO_URL}
      - DATA_PATH=${DATA_PATH}
      - ORIGIN=${ORIGIN}
    restart: unless-stopped

  backend-dev:
    extends: backend
    profiles: ["development"]
    container_name: backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend/src:/app/src
      - ./backend/pom.xml:/app/pom.xml:ro
      - maven-cache:/root/.m2
      - ${DATA_PATH}/photos:/app/photos

  backend-prod:
    extends: backend
    profiles: ["production"]
    container_name: backend
    volumes:
      - maven-cache:/root/.m2
      - ${DATA_PATH}/photos:/app/photos

  mongodb:
    image: mongo:7
    ports:
      - "27017:27017"
    volumes:
      - ${DATA_PATH}/mongo_data:/data/db
    networks:
      - catalog_network
    restart: unless-stopped

networks:
  catalog_network:
    driver: bridge

volumes:
  maven-cache:
